// import Slider from '@react-native-community/slider';
import { useEffect, useState } from 'react';
import { Linking, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

const ResultScreen = ({ route }) => {
    const { breakdown, inputs } = route.params;

    // Initial profit margin from inputs
    const [profitMargin, setProfitMargin] = useState(inputs.profit_margin_percent);
    const [finalFob, setFinalFob] = useState(breakdown.final_fob_per_pc);

    const handleProfitMarginChange = (value) => {
        // Allow empty string, minus sign, decimal point, or valid decimal numbers
        if (value === '' || value === '-' || value === '.' || /^-?\d*\.?\d*$/.test(value)) {
            setProfitMargin(value);
        }
    };

    useEffect(() => {
        // Recalculate locally when profit margin changes
        // Only calculate if profitMargin is a valid number
        const margin = parseFloat(profitMargin);
        if (isNaN(margin)) {
            return; // Don't update if invalid
        }
        
        // Formula: (CostWithCommercial * (1 + Profit/100)) / 12
        const costWithComm = breakdown.cost_with_commercial_per_doz;
        const newFinalCost = costWithComm * (1 + (margin / 100.0));
        const newFob = newFinalCost / 12.0;
        setFinalFob(newFob);
    }, [profitMargin]);

    const handleShare = () => {
        const message = `Quote for ${inputs.style_name}:
Fabric: ${inputs.fabric_type} ${inputs.gsm} GSM
Consumption: ${breakdown.total_fabric_req_kg_doz} kg/dz
Target Price: $${finalFob.toFixed(2)}/pc
Generated by MerchMate.`;

        const url = `whatsapp://send?text=${encodeURIComponent(message)}`;
        Linking.openURL(url).catch(() => {
            // Fallback if WhatsApp is not installed
            Linking.openURL(`https://wa.me/?text=${encodeURIComponent(message)}`);
        });
    };

    return (
        <ScrollView style={styles.container}>
            <View style={styles.headerCard}>
                <Text style={styles.label}>FINAL FOB PRICE</Text>
                <Text style={styles.price}>$ {finalFob.toFixed(2)} <Text style={styles.unit}>/ pc</Text></Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Adjust Profit Margin: {typeof profitMargin === 'number' ? profitMargin.toFixed(1) : profitMargin}%</Text>
                {/* Temporary replacement for Slider */}
                <TextInput
                    style={{ borderWidth: 1, borderColor: '#ddd', padding: 10, borderRadius: 5 }}
                    keyboardType="decimal-pad"
                    value={String(profitMargin)}
                    onChangeText={handleProfitMarginChange}
                />
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Cost Breakdown (per Doz)</Text>
                <View style={styles.tableRow}>
                    <Text style={styles.tableLabel}>Fabric Cost</Text>
                    <Text style={styles.tableValue}>$ {breakdown.fabric_cost_per_doz}</Text>
                </View>
                <View style={styles.tableRow}>
                    <Text style={styles.tableLabel}>Print/AOP</Text>
                    <Text style={styles.tableValue}>$ {inputs.aop_print_cost_per_doz}</Text>
                </View>
                <View style={styles.tableRow}>
                    <Text style={styles.tableLabel}>Accessories</Text>
                    <Text style={styles.tableValue}>$ {inputs.accessories_cost_per_doz}</Text>
                </View>
                <View style={styles.tableRow}>
                    <Text style={styles.tableLabel}>CM Cost</Text>
                    <Text style={styles.tableValue}>$ {inputs.cm_cost_per_doz}</Text>
                </View>
                <View style={[styles.tableRow, { borderTopWidth: 1, marginTop: 5, paddingTop: 5 }]}>
                    <Text style={[styles.tableLabel, { fontWeight: 'bold' }]}>Total Cost</Text>
                    <Text style={[styles.tableValue, { fontWeight: 'bold' }]}>$ {breakdown.total_cost_per_doz}</Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Consumption Details</Text>
                <Text>Basic Cons: {breakdown.basic_consumption_kg_doz} kg/doz</Text>
                <Text>Total Req (with {inputs.wastage_percent}%): {breakdown.total_fabric_req_kg_doz} kg/doz</Text>
            </View>

            <TouchableOpacity style={styles.whatsappButton} onPress={handleShare}>
                <Text style={styles.whatsappText}>Share Quote to WhatsApp</Text>
            </TouchableOpacity>
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, padding: 20, backgroundColor: '#f5f5f5' },
    headerCard: { backgroundColor: '#007bff', padding: 30, borderRadius: 15, alignItems: 'center', marginBottom: 20 },
    label: { color: 'rgba(255,255,255,0.8)', fontSize: 16, fontWeight: 'bold' },
    price: { color: '#fff', fontSize: 48, fontWeight: 'bold' },
    unit: { fontSize: 20 },
    section: { backgroundColor: '#fff', padding: 20, borderRadius: 10, marginBottom: 15, elevation: 2 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#333' },
    tableRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    tableLabel: { fontSize: 16, color: '#555' },
    tableValue: { fontSize: 16, color: '#333', fontWeight: '500' },
    whatsappButton: { backgroundColor: '#25D366', padding: 15, borderRadius: 10, alignItems: 'center', marginBottom: 30 },
    whatsappText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
});

export default ResultScreen;
